version: '3.7'

services:
    prowlarr:
      image: ghcr.io/linuxserver/prowlarr:develop
      container_name: prowlarr
      networks:
            - backend
      env_file:
          - /docker-nas/docker-templates/prowlarr/.env
      environment:
        - PUID=${GLOBAL_UID}
        - PGID=${GLOBAL_GID}
        - UMASK_SET=002
      volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - '/etc/timezone:/etc/timezone:ro'
        - "/docker-nas/docker-data/prowlarr:/config"
        - "/docker-nas/home:/docker-nas/home:shared"
      # ports:
      #   - 9696:9696
      restart: unless-stopped
