version: '3.7'

services:
    nginx:
        container_name: nginx
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/lochnas/docker-templates/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "/lochnas/docker-data/nginx/.htpasswd:/etc/nginx/.htpasswd:ro"
            - "/lochnas/docker-data/nginx/templates:/etc/nginx/templates:ro"
            - "/lochnas/docker-data/nginx/logs:/etc/nginx/logs"
            - "/lochnas/docker-data/letsencrypt:/etc/letsencrypt"
            - "/lochnas/docker-data/certbot:/var/www/certbot"
        networks:
            - backend
        env_file:
            - /lochnas/docker-templates/nginx/.env
        environment:
            - GLOBAL_DOMAIN
        ports:
            - '443:443/tcp'
            - '80:80/tcp'

        restart: unless-stopped
        image: 'nginx:latest'