version: '3.7'

services:
    collabora:
        container_name: collabora
        build: 
          context: /docker-nas/docker-templates/collabora/dockerimage/
          dockerfile: Dockerfile
        env_file:
            - /docker-nas/docker-templates/collabora/.env
        environment:
            - TZ=America/New_York
            - 'extra_params=--o:ssl.enable=false --o:net.proto=IPv4 --o:ssl.termination=true --o:net.post_allow.host[0]=172\.[0-9\.]+ --o:storage.wopi.host[0]=172\.[0-9\.]+'
            - DONT_GEN_SSL_CERT=true
            - server_name=office.${GLOBAL_DOMAIN}
            - username=${GLOBAL_COLLABORA_USERNAME}
            - password=${GLOBAL_COLLABORA_PASSWORD}
            - no_proxy=cloud.rodriguez.systems
        cap_add:
            - MKNOD
        networks:
            - backend
        restart: unless-stopped
        privileged: true

