version: '3.7'

services:
    collabora:
        container_name: collabora
        build: 
          context: /docker-nas/docker-templates/collabora/dockerimage/
          dockerfile: Dockerfile
        env_file:
            - /docker-nas/docker-templates/collabora/.env
        environment:
            - TZ=America/New_York
            - 'extra_params=--o:ssl.enable=false --o:ssl.termination=true'
            - DONT_GEN_SSL_CERT=true
            - domain=cloud\.rodriguez\.systems
            - server_name=office.${GLOBAL_DOMAIN}
            - aliasgroup1=cloud.${GLOBAL_DOMAIN}
            - dictionaries=en_US
        cap_add:
            - MKNOD
        networks:
            - backend
        # volumes:
        #     - '/etc/localtime:/etc/localtime:ro'
        #     - '/etc/timezone:/etc/timezone:ro'
        restart: unless-stopped
        privileged: true
        healthcheck:
            test: ["CMD", "wget", "https://office.${GLOBAL_DOMAIN}/", "-O", "/dev/null"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 5s

