server:
    debug: false
    global-env:
        - "GLOBAL_DOMAIN=domain.com"
        - "GLOBAL_EMAIL=email@domain.com"
        - "GLOBAL_GID=33"
        - "GLOBAL_UID=33"
    port: 4000
    ddns:
        ip: 0.0.0.0
        url:
            - http://ddnsupdate.com
            - http://ddnsupdate.com
        notification:
            enabled: true
            service: telegram
    notifications:
        subject: Docker Nas Server
        enabled: true
        services:
            email:
                enabled: false
                server: 
                from: 
                username: 
                password: 
                receivers: 
                    - someuser@yahoo.com
            telegram:
                enabled: true
                token: 
                receivers:
                    - -1234567890