version: '3.7'
networks:
    backend:
        driver: bridge
        driver_opts:
            com.docker.network.bridge.enable_icc: "true"
            com.docker.network.bridge.enable_ip_masquerade: "true"
            com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
            com.docker.network.bridge.name: "backend"
            com.docker.network.driver.mtu: 1500
        ipam:
            driver: default
            config:
                - subnet: 172.33.0.0/16
services:
    autoheal:
        container_name: autoheal
        restart: unless-stopped
        image: willfarrell/autoheal
        environment:
            - AUTOHEAL_CONTAINER_LABEL=all
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - /var/run/docker.sock:/var/run/docker.sock
