#https://composerize.com/
version: '3.7'

services:
    phpmyadmin:
        container_name: phpmyadmin
        networks:
            - backend
        # env_file:
        #     - docker-templates/phpmyadmin/.env
        environment:
            - PMA_HOST=mariadb
        image: 'phpmyadmin/phpmyadmin:latest'
        ports:
            - '8080:80/tcp'
#        healthcheck:
#            test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
#            interval: 1m
#            timeout: 10s
#            retries: 3
#            start_period: 15s
