version: '3.7'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    networks:
        - backend
    environment:
        - PUID=${GLOBAL_UID}
        - PGID=${GLOBAL_GID}
        # - TZ=Europe/London
    volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - '/etc/timezone:/etc/timezone:ro'
        - "/docker-nas/docker-data/heimdall/config:/config"
    env_file:
        - /docker-nas/docker-templates/heimdall/.env
    # ports:
    #     - 80:80
    restart: unless-stopped