version: '3.4'

services:
    hass:
        container_name: homeassistant
        network_mode: host
        healthcheck:
            test: ["CMD", "curl", "-f", "https://hass.${GLOBAL_DOMAIN}"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 15s
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/docker-nas/docker-data/homeassistant:/config"
        restart: unless-stopped
        image: 'homeassistant/home-assistant:stable'
        env_file:
            - /docker-nas/docker-templates/homeassistant/.env
