version: '3.4'

services:
    hass:
        container_name: homeassistant
        network_mode: host
        healthcheck:
            test: ["CMD", "curl", "-f", "https://hass.${GLOBAL_DOMAIN}"]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 15s
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/lochnas/docker-data/homeassistant:/config"
        devices:
            - ${GLOBAL_DEVICE_0}:/dev/ttyUSB0
            - ${GLOBAL_DEVICE_1}:/dev/ttyUSB1
            - ${GLOBAL_DEVICE_2}:/dev/ttyUSB2
            - ${GLOBAL_DEVICE_3}:/dev/ttyUSB3
        restart: unless-stopped
        image: 'homeassistant/home-assistant:stable'
        env_file:
            - /lochnas/docker-templates/homeassistant/.env
