version: '3.7'

services:
    minecraftbedrock:
        container_name: minecraftbedrock
        image: itzg/minecraft-bedrock-server
        ports:
            - "19132:19132/udp"
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/lochnas/docker-data/minecraft-bedrock:/data"
        env_file:
            - /lochnas/docker-templates/minecraft-bedrock/.env
        environment:
            REPLACE_ENV_VARIABLES: "TRUE"
        restart: unless-stopped
