#https://composerize.com/
version: '3.7'

services:
    minecraftbedrock:
        container_name: minecraftbedrock
        image: itzg/minecraft-bedrock-server
        ports:
            - "19132:19132/udp"
        volumes:
            - "${GLOBAL_ROOT}/docker-data/minecraft-bedrock:/data"
        # env_file:
        #     - docker-templates/minecraft-bedrock/.env
        environment:
            EULA: "TRUE"
            ENABLE_RCON: "false"
            #RCON_PASSWORD: "testing"
            #RCON_PORT: 28016
            # enable env variable replacement
            REPLACE_ENV_VARIABLES: "TRUE"
            # define an optional prefix for your env variables you want to replace
            #ENV_VARIABLE_PREFIX: "CFG_"
            # and here are the actual variables
            #CFG_DB_HOST: "http://localhost:3306"
            #CFG_DB_NAME: "minecraft"
            #CFG_DB_PASSWORD_FILE: "/run/secrets/db_password"
        restart: unless-stopped
