#https://composerize.com/
version: '3.7'

services:
    minecraftbedrock:
        container_name: minecraftbedrock
        image: itzg/minecraft-bedrock-server
        ports:
            - "19132:19132/udp"
        volumes:
            - "/docker-nas/docker-data/minecraft-bedrock:/data"
        env_file:
            - /docker-nas/docker-templates/minecraft-bedrock/.env
        environment:
            EULA: "TRUE"
            REPLACE_ENV_VARIABLES: "TRUE"
        restart: unless-stopped
