version: '3.7'

services:
    portainer:
        container_name: portainer
        networks:
            - backend
        env_file:
            - /lochnas/docker-templates/portainer/.env
        volumes:
            - "/lochnas/docker-data/portainer:/data"
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: unless-stopped
        image: 'portainer/portainer-ce:latest'
        ports:
            - '9000:9000/tcp'
