version: '3.7'

services:
    minecraft:
        container_name: minecraft
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/docker-nas/docker-data/minecraft:/data"
        env_file:
            - /docker-nas/docker-templates/minecraft/.env
        environment:
            REPLACE_ENV_VARIABLES: "TRUE"
        restart: unless-stopped
