version: '3.7'

services:
    minecraft:
        container_name: minecraft
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/lochnas/docker-data/minecraft:/data"
        env_file:
            - /lochnas/docker-templates/minecraft/.env
        environment:
            - REPLACE_ENV_VARIABLES="TRUE"
            - UID=${GLOBAL_UID}
            - GID=${GLOBAL_GID}
        restart: unless-stopped
