#https://composerize.com/
version: '3.7'

services:
    minecraft:
        container_name: minecraft
        image: itzg/minecraft-server
        ports:
            - "25565:25565"
        volumes:
            - "/docker-nas/docker-data/minecraft:/data"
        env_file:
            - /docker-nas/docker-templates/minecraft/.env
        environment:
            EULA: "TRUE"
            REPLACE_ENV_VARIABLES: "TRUE"
        restart: unless-stopped
