version: '3.7'

services:
    nextcloud:
        container_name: nextcloud
        env_file:
            - /docker-nas/docker-templates/nextcloud/.env
        # hostname: cloud.${GLOBAL_DOMAIN} # Interferes with collabora hitting cloud.domain endpoint
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/docker-nas/docker-data/nextcloud/html:/var/www/html"
            - "/docker-nas/home:/docker-nas/home:shared"
        restart: unless-stopped
        networks:
            - backend
        build: 
          context: /docker-nas/docker-templates/nextcloud/dockerimage/
          dockerfile: Dockerfile
        environment:
            - MYSQL_HOST=mariadb
        links:
            - mariadb
        depends_on:
            - mariadb
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "https://cloud.${GLOBAL_DOMAIN}"]
        #     interval: 15m
        #     timeout: 30s
        #     retries: 3
        #     start_period: 25s
    mariadb:
        container_name: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF
        env_file:
            - /docker-nas/docker-templates/nextcloud/.env
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/docker-nas/docker-data/mariadb:/var/lib/mysql"
        restart: unless-stopped
        networks:
            - backend
        environment:
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        image: 'mariadb:10.7'
        #10.8.3 or latest seems to have issues. Lets pin this version
