#https://composerize.com/
version: '3.7'

services:
    nextcloud:
        container_name: nextcloud
        hostname: cloud.${GLOBAL_DOMAIN}
        volumes:
            - "${GLOBAL_ROOT}/docker-data/nextcloud/html:/var/www/html"
            - "${NEXTCLOUD_DATA}:/raid"
        restart: unless-stopped
        networks:
            - backend
        build: 
          context: ./docker-templates/nextcloud/dockerimage/
          dockerfile: Dockerfile
        # env_file:
        #     - docker-templates/nextcloud/.env
        environment:
            - MYSQL_HOST=mariadb
        links:
            - mariadb
        depends_on:
            - mariadb
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "https://cloud.${GLOBAL_DOMAIN}"]
        #     interval: 15m
        #     timeout: 30s
        #     retries: 3
        #     start_period: 25s
    mariadb:
        container_name: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb_read_only_compressed=OFF
        volumes:
            - "${GLOBAL_ROOT}/docker-data/mariadb:/var/lib/mysql"
        restart: unless-stopped
        networks:
            - backend
        # env_file:
        #     - docker-templates/ark/.env
        environment:
            - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
            - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
        image: 'mariadb:latest'
