version: '3.7'

services:
    samba:
        container_name: samba
        build: 
            context: /lochnas/docker-templates/samba/dockerimage/
            dockerfile: Dockerfile
        network_mode: host
        restart: unless-stopped
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/lochnas/docker-data/samba/smb.conf:/etc/samba/smb.conf"
            - "/lochnas/home:/lochnas/home:shared"
            - "/lochnas/docker-data/minecraft:/lochnas/docker-data/minecraft:shared"
        env_file:
            - /lochnas/docker-templates/samba/.env
