#https://composerize.com/
version: '3.7'

services:
    samba:
        container_name: samba
        build: 
            context: /docker-nas/docker-templates/samba/dockerimage/
            dockerfile: Dockerfile
        network_mode: host
        restart: unless-stopped
        volumes:
            - "/docker-nas/docker-data/samba/smb.conf:/etc/samba/smb.conf"
            - "/docker-nas/home:/docker-nas/home:shared"
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        env_file:
            - /docker-nas/docker-templates/samba/.env
        environment:
            - SAMBA_USERMAP
