version: '3.7'

services:
    ark:
        container_name: ark
        restart: unless-stopped
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/docker-nas/docker-data/ark:/ark"
        network_mode: host
        image: 'turzam/ark:latest'
        env_file:
            - /docker-nas/docker-templates/ark/.env
        environment:
            - "UID=${GLOBAL_UID}"
            - "GID=${GLOBAL_GID}"
