version: '3.7'

services:
    honeygain:
        container_name: honeygain
        build: 
            context: /lochnas/docker-templates/honeygain/dockerimage/
            dockerfile: Dockerfile
        env_file:
            - /lochnas/docker-templates/honeygain/.env
        restart: unless-stopped