# # version: '3.7'

# nzbget:
#     image: linuxserver/nzbget
#     container_name: nzbget
#     volumes:
#         - ${CONFIG}/nzbget:/config
#         - ${DATA}/Downloads/complete:/complete
#         - ${DATA}/Downloads:/downloads
#         - ${DATA}/data:/data
#         #    - 6789:6789
#     environment:
#         - PUID=${GLOBAL_UID}
#         - PGID=${GLOBAL_GID}
#     restart: unless-stopped