#https://composerize.com/
version: '3.7'

services:
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
            - backend
      env_file:
          - /docker-nas/docker-templates/sonarr/.env
      environment:
        - PUID=${GLOBAL_UID}
        - PGID=${GLOBAL_GID}
        - UMASK_SET=002
      volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - '/etc/timezone:/etc/timezone:ro'
        - "/docker-nas/docker-data/sonarr:/config"
        - "/docker-nas/home:/docker-nas/home:shared"
      # ports:
      #   - 8989:8989
      restart: unless-stopped
