version: '3.7'

services:
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
            - backend
      deploy:
          resources:
              limits:
                  memory: 4G #Cap it to 4GB of ram usage. This wont affect systems under 4GB
      env_file:
          - /lochnas/docker-templates/sonarr/.env
      environment:
        - PUID=${GLOBAL_UID}
        - PGID=${GLOBAL_GID}
        - UMASK_SET=002
      dns: #Force it to go out so it hits the nginx proxy
          - 1.1.1.1
          - 8.8.8.8
      volumes:
        - '/etc/localtime:/etc/localtime:ro'
        - '/etc/timezone:/etc/timezone:ro'
        - "/lochnas/docker-data/sonarr:/config"
        - "/lochnas/home:/lochnas/home:shared"
      # ports:
      #   - 8989:8989
      restart: unless-stopped
