#https://composerize.com/
version: '3.7'

services:
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      networks:
            - backend
      # env_file:
      #     - docker-templates/sonarr/.env
      environment:
        - PUID=${GLOBAL_UID}
        - PGID=${GLOBAL_GID}
        - TZ=America/New_York
        - UMASK_SET=002
      volumes:
        - "${GLOBAL_ROOT}/docker-data/sonarr:/config"
        - "${PLEX_DATA}/TV:/tv"
        - "${PLEX_DATA}/transmission:/data"
      # ports:
      #   - 8989:8989
      restart: unless-stopped
