version: '3.7'

services:
    transmission:
        container_name: transmission
        command: "'dumb-init' '/etc/openvpn/start.sh'"
        networks:
            - backend
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/docker-nas/docker-data/transmission/home:/data/transmission-home"
            - "/docker-nas/docker-data/transmission/scripts:/scripts"
            - "/docker-nas/docker-data/transmission/config:/config"
            - "/docker-nas/docker-data/transmission/custom:/etc/openvpn/custom:ro"
            - "/docker-nas/home:/docker-nas/home:shared"
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        dns:
            - 1.1.1.1
            - 8.8.8.8
        env_file:
            - /docker-nas/docker-templates/transmission/.env
        environment:
            - PUID=${GLOBAL_UID}
            - PGID=${GLOBAL_GID}
        image: 'haugene/transmission-openvpn:latest'
        ports:
            - '9091:9091'
