#https://composerize.com/
version: '3.7'

services:
    plex:
        container_name: plex
        volumes:
            - "${GLOBAL_ROOT}/docker-data/plex:/config"
            - '/tmp/transcode:/transcode'
            - "${PLEX_DATA}:/data:shared"
        restart: unless-stopped
        network_mode: host
        # env_file:
        #     - docker-templates/plex/.env
        environment:
            - CHANGE_CONFIG_DIR_OWNERSHIP=true
            - HOME=/config
            - "PLEX_UID=${GLOBAL_UID}"
            - "PLEX_GID=${GLOBAL_GID}"
        image: 'plexinc/pms-docker:latest'
