version: '3.7'

services:
    plex:
        container_name: plex
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
            - '/etc/timezone:/etc/timezone:ro'
            - "/lochnas/docker-data/plex:/config"
            - '/tmp/transcode:/transcode'
            - "/lochnas/home:/lochnas/home:shared"
        restart: unless-stopped
        network_mode: host
        env_file:
            - /lochnas/docker-templates/plex/.env
        environment:
            - CHANGE_CONFIG_DIR_OWNERSHIP=true
            - HOME=/config
            - "PLEX_UID=${GLOBAL_UID}"
            - "PLEX_GID=${GLOBAL_GID}"
        image: 'plexinc/pms-docker:latest'
